services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__MongoDb=mongodb://mongo/tiles
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
